Skip processing `rule.each` on optional value when input is nil
When a key has a `maybe` macro, nil values are valid. However, if a
`rule.each` is specified on that key, an error is throw saying:

```
`block in each': undefined method `each_with_index' for nil:NilClass (NoMethodError)
```