Fix using optional string keys when using sanitizer
Previously using `optional('height').filled` produced
```
  NoMethodError:
    undefined method `visit_height' for #<Dry::Types::Compiler:0x007fdf3f9eb530 @registry=Dry::Types>
```
when the input_processor was set to sanitizer.

Input processor compiler was checking only if the key was a symbol. Now
it also checks for string keys.

Fixes #386